# Generated by Django 2.2.4 on 2019-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_book', '0008_remove_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='user_book/'),
        ),
    ]
