# Generated by Django 2.2.4 on 2019-09-12 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_book', '0009_auto_20190827_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_year',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='123', max_length=250, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=2019, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/%Y/%m/%d/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
